### ISSUE TITLE
Wrong point cloud data generation from 3D Lidar component

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#187]
Hi Rapyuta-robotics team,
I am testing an example 3D lidar component(Ouster OS032) with default settings as below:
![OusterComponentSettings](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/23667624/708a3c82-ae2c-42ef-a4e9-8034a8a48ed7)  
  
When starting the simulation, rays show the correct point clouds as configuration.
![OusterRaycast](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/23667624/0d30951c-d839-4934-81d6-c884ca7755db)  
  
However, rviz shows weird point clouds as below:
![RvizPlot](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/23667624/3f396c5d-c6cc-4322-ad9f-48a4aea12c1a)

**Comment by michaelaeriksen** [comment]
I'm relative new to Unreal and this plugin would you mind sharing how you add the 3d lidar to a scene?

**Comment by Hisham178** [comment]
I'm having the same issues. Please let me know if there any work around this

**Comment by yuokamoto** [comment]
Sorry for inconvinence
I'm investigating the issue now. Not sure how much time I need to fix since I only have time to investigate in weekend.

**Comment by yuokamoto** [comment]
I found cause luckily and created PR.
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/192
