### ISSUE TITLE
Frame rate drop

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#194]
Hi @yuokamoto,
I am testing a sensor component and figuring out that there is a frame drop issue. As you can see in the following video, the frame rate of each sensor drops by about 40% from the set value. 
- ROS2CameraComponent : 15 Hz -> 8~9Hz
- ROS23DLidarComponent : 10 Hz -> 6Hz

![framedrop](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/23667624/6723f62b-4b02-40cb-8210-868d28823d0f)

Do you know if there is anything I need to set up to address this?

**Comment by yuokamoto** [comment]
How about the /clock topic rate or real time factor of the simulation?

**Comment by james-yoo** [comment]
@yuokamoto 
Thanks for your quick response. The '/clock' topic was showing 60 Hz, and the fps in Unreal Editor was also showing 60. I am currently testing under UE 5.2.1 and figured out there is a framerate issue. I set the 'Fixed Frame Rate' parameter to 100 as below: 
![Screenshot from 2023-08-06 12-30-28](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/23667624/75feb945-94e6-491c-b1a0-e6e815e3668c)
However, I've noticed that no matter what settings(VSM, Lumen, Nanite, and so on) I change, it always caps at 60 FPS(even in empty black scenes). 
![Screenshot from 2023-08-06 12-34-26](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/23667624/d17f3fa7-4ba2-471b-9705-f151e7e5b1a6)
I will need to check this further, but I believe this is an issue with Unreal Engine itself.

**Comment by yuokamoto** [comment]
Thanks for your investigation.
I'm not sure the root cause of the issue. 

FYI
Since UE's frequency is not normally high, e.g. 30hz, I created this custom timer and used inside from publisher.
https://github.com/rapyuta-robotics/rclUE/blob/7613773cd4c1226957603d705d68a2d2b4a69166/Source/rclUE/Public/rclcUtilities.h#L174

**Comment by james-yoo** [comment]
@yuokamoto 
Thansk for the response. This issue was mistake on my side and resolved by use UBT on compile time.
I apologies for the inconvenience.

**Comment by pabsan-0** [comment]
@james-yoo Hi, could you please give more details on this? Do you mean compiling the world and running it in isolation rather than in the editor?
