### ISSUE TITLE
Time Sync

### ISSUE THREAD

**Issue by Hisham178** [rapyuta-robotics/RapyutaSimulationPlugins#200]
How do we sync time, because I noticed time from odom and sensors up untill nano seconds. But from blueprint only in seconds?

**Comment by yuokamoto** [comment]
1) Since nano seconds is defined as unsigned int which is not supported in BP, nano seconds can not be exposed.
2) Since time in header is fill from UE time, such as `UGameplayStatics::GetTimeSeconds(GetWorld())`, you can get/save time when odom is published inside UE.

**Comment by Hisham178** [comment]
I just found out, you can get up to nano second by doing this. With sim time is true and clock topic. I can finally sync my time across all my nodes

![Screenshot from 2023-08-29 15-39-38](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/110361659/89bdd41c-6edc-4647-b59c-8dffe4072333)
