### ISSUE TITLE
Is there any way to publish transform?

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#209]
Hi,
According to the [document](https://rapyutasimulationplugins.readthedocs.io/en/devel/overview.html), ARRBaseRobot has only basic interface such as /cmd_vel, /odom, /joint_states , /joint_commands.  I'd like to publish a transform (such as /tf or /static_tf) for a custom robot, but I can't find a way to do so.

Since Unreal's static meshes correspond to urdf's 'link' attribute, and physics components correspond to urdf's 'joint' attribute, isn't that possible to publish the transform automatically based on the hierarchy of robot actor?

**Comment by yuokamoto** [comment]
Hi,
There are multiple options
1.  You can use [robot_state_publisher](http://wiki.ros.org/robot_state_publisher)  which subscribes /joint_states and publish /tf but requires urdf as robot_description
2.  Implement tf publisher using [TFPublisher](https://rapyutasimulationplugins.readthedocs.io/en/devel/doxygen_generated/html/d2/d2a/class_u_r_r_r_o_s2_t_f_publisher.html). it shouldn't be difficult but may need to think about multiple parameter such as offset from static mesh origin to link origin

**Comment by yuokamoto** [comment]
wip branch
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/tree/joint_tf_publisher

**Comment by yuokamoto** [comment]
Sorry for taking long.
Created PR https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/213

**Comment by james-yoo** [comment]
Hi @yuokamoto,
I would like to know how to apply this 'joint tf publisher' to a mobile robot. A simple screenshot or documentation update would be great.

**Comment by yuokamoto** [comment]
Hi,
- need to enable bPublishJointTfPublisher of RRROS2Interface.
https://rapyutasimulationplugins.readthedocs.io/en/devel/doxygen_generated/html/d6/d64/class_u_r_r_robot_r_o_s2_interface.html#af208c8352e4fe16c84fa837afc8e5966
- If joint is made from RRJointComponent, you can publish tf by adding Links and Joints from following methods. Please check BP_PandaArm's construction script as a example. 
https://rapyutasimulationplugins.readthedocs.io/en/devel/doxygen_generated/html/df/d13/class_a_r_r_base_robot.html#a8201f7342a882d457ed9e5d36cb4d14f
https://rapyutasimulationplugins.readthedocs.io/en/devel/doxygen_generated/html/df/d13/class_a_r_r_base_robot.html#aa9671e0d7ab5981d2af32dd58b3937af
- if joint is not RRJointComponent, I added PR to add publish tf between links. https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/217
![image (3)](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/16463135/9b1ac3a4-df6e-494b-a3b9-a6a64460d7ce)

**Comment by james-yoo** [comment]
@yuokamoto,
Looks great!  Thanks for your quick response!
