### ISSUE TITLE
Support depth camera

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#225]
Hi rapyuta-robotics team,
Currently, RapyutaSimulationPlugins only supports CameraComponent for RGB image. Any plan to support depth image?

**Comment by yuokamoto** [comment]
RapyutaSimulationPlugins has 3d lidar plugin. I'm not sure but can't we use 3d lidar plugin for deth camera as well?

**Comment by james-yoo** [comment]
@yuokamoto 
3DLiDARComponent uses 'AsyncLineTraceByChannel' method to check collision between ray and object, it is not suitable for obtaining dense depth image like below:
![image](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/23667624/3c58dc54-bafd-4465-83dc-a9b74a5873e1)

**Comment by yuokamoto** [comment]
I can create something by changing camera postprocess to SceneDepth. 
it is easy in bp but not sure  how I can set same thing in C++, will investigate more alter

![image](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/16463135/dd60ba0f-bb42-4590-b88c-a70805b7d1d5)

**Comment by yuokamoto** [comment]
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/231
