### ISSUE TITLE
Camera sensor support?

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#23]
Hi Rapyuta Robotics team,

Currently, this plugin only supports Lidar sensor.
Do you have any plan to support camera sensor? I think it can be implemented using the CaptureScene2d class.

**Comment by yuokamoto** [comment]
Thanks for you interest.
We have a plan to support but haven't started working on yet. Let us estimate effort.

**Comment by yuokamoto** [comment]
created draft pr for rgb camera
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/24
