### ISSUE TITLE
Where is the "SceneDepth" material come from?

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#263]
Hi @yuokamoto,

I would like to control a depth map of the ROS2CameraComponent. It uses the "SceneDepth" material for blending as below:

https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/blob/be7a97715340d189a2a358aece86cfb8714f0384/Source/RapyutaSimulationPlugins/Private/Sensors/RRROS2CameraComponent.cpp#L27

Where is this material come from?

Cheers

**Comment by yuokamoto** [comment]
I think it is comes  from here
https://github.com/EpicGames/UnrealEngine/blob/072300df18a94f18077ca20a14224b5d99fee872/Engine/Config/BaseEngine.ini#L2738

![image](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/16463135/0aff0fef-ada9-4a30-94dd-449ca868123a)

**Comment by james-yoo** [comment]
@yuokamoto 
Thank you so much.
