### ISSUE TITLE
Create custom sensors components

### ISSUE THREAD

**Issue by dbarrita** [rapyuta-robotics/RapyutaSimulationPlugins#276]
Hi,
I want to create my own list of sensors and save it in blueprints so I can copy the folder that contains all in each project and don't have to configure the properties and add the meshes in each project/robot. I want this BP to contain the mesh of the sensor and the RR3DLidar component configured with the properties of that sensor. I have seen that in the turtlebot example to add a sensor you have to add the mesh first and later the RR3DLidar component. Is there a way to create one component that contains both? Thanks in advance!

**Comment by yuokamoto** [comment]
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/16463135/e3e358e7-0a4b-4476-aa89-407c0448848b

Hello, you can create Actor which has both mesh and sensor.

**Comment by dbarrita** [comment]
Thanks! I have followed the video to create the BP with my Lidar and now I want to add this actor to my robot BP. I have seen that I can add the sensor BP to the robot BP using a child actor, the problem is that I don't know if I can edit the properties of the Lidar using a child actor. For example, if I want to put two Lidars of the same model in my robot, I need to access to the variable topic name and edit it in order to have to have a topic for each sensor. Is this possible?

**Comment by yuokamoto** [comment]
I see. I can't find the option to edit in window...
it is not ideal but I can edit  variable  from construction script
![image](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/16463135/c970bb71-40c1-4bc3-8052-85f176e8d22d)

**Comment by dbarrita** [comment]
Hi again,
Finally what I have done is created variables for the color and the topic name in the sensor BP and I have seen that can be edited in the Child Actor Template.
![ChildActorOptions](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/90312492/b53c8e62-c0b2-4af3-a0f3-1f1d0d2997c3)
