### ISSUE TITLE
Calculation of angular velocity of the wheel

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#299]
Hi @yuokamoto,

To calculate the rotational speed of the wheel, shouldn't the linear velocity be divided by the wheel radius, not by the perimeter?
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/blob/bf9cc4f9227aa6a84b9da4cafc473c4b428e20dd/Source/RapyutaSimulationPlugins/Private/Drives/DifferentialDriveComponent.cpp#L40-L41

**Comment by yuokamoto** [comment]
I originally think so as well but it seems SetAngularVelocityTarget input is rotation/s
![image](https://github.com/user-attachments/assets/efc27483-5155-4415-96b4-c4884e1f247d)

**Comment by james-yoo** [comment]
@yuokamoto 
Ah, got it! Thanks for sharing :)
