### ISSUE TITLE
Update document

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#300]
Hi @yuokamoto,

Do you have any plan to update document regarding of the character control(https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/264)? I can not find any guide about AI controlled character, ROS 2 interface in the [online document](https://rapyutasimulationplugins.readthedocs.io/en/devel/).

**Comment by yuokamoto** [comment]
Thanks for your comment. yes I'm working on adding 1) external devices such as conveyor, elevator, etc, 2) character control.

I;ll let you know when it become ready.

**Comment by yuokamoto** [comment]
PR is in review
https://rapyutasimulationplugins.readthedocs.io/en/doc_update2/external_devices.html
