### ISSUE TITLE
Frameid is missing in camera component

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#33]
Thanks for updating camera plugin #24.

I can see image topic(ros2 topic list) but cannot display via rviz2 because there is no 'frame_id' on topic.
It would be nice to add 'UPROPERTY' variable to set the frame_id.

**Comment by yuokamoto** [comment]
Thansk for reporting.

This refactor PR should solve issue
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/39

**Comment by james-yoo** [comment]
@yuokamoto,
Thanks. Issue resolved.
